spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root2025
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242 # This is the front end page we will redirect the user to